version: '3.7'
services:
  app:
    build: './app'
    volumes:
      - './app:/home/ralsnet_channel:cached'
    ports:
      - '55555:8000'
    links:
      - db
    command: php artisan serve --host=0.0.0.0
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rals_channel
    volumes:
      - './db/data:/var/lib/mysql'
    ports:
      - '33066:3306'